### ISSUE TITLE
Support platforms with ncurses 6.x instead of ncurses 5.x

### ISSUE THREAD

**Issue by big-guy** [adammurdoch/native-platform#18]
As an example:
https://discuss.gradle.org/t/terminal-problems/20319

Newer distributions are including only ncurses 6.x (released in 2015) instead of ncurses 5.x. 

You can sometimes work around this problem by symlinking ncurses.so.5 to ncurses.so.6 or installing ncurses-compat-libs (if the distribution has it).

**Comment by adammurdoch** [comment]
This is fixed in 0.12.
