### ISSUE TITLE
freebsd artefacts missing in 0.12 and 0.13 releases

### ISSUE THREAD

**Issue by ligee** [adammurdoch/native-platform#23]
both variants of freebsd artefacts for version 13 (and some others) are missing in the repo.

**Comment by adammurdoch** [comment]
There are 4 variants, from 0.12 onwards, so the names have changed.

For example: https://repo.gradle.org/gradle/webapp/#/artifacts/browse/tree/General/libs-releases-local/net/rubygrapefruit/native-platform-freebsd-amd64-libcpp
