### ISSUE TITLE
Platforms built with `--enable-widec` only have `libncursesw.so`

### ISSUE THREAD

**Issue by big-guy** [adammurdoch/native-platform#24]
On distributions (like Arch Linux) that have been built with `--enable-widec`, ncurses produces only a `libncursesw.so` (note the w).

Since `native-platform` links against `libncurses.so` (5 or 6), Gradle falls back to a plain terminal.

I don't think it's necessarily safe, but symlinking `libncurses.so.6` to `libncursesw.so` worked.

**Comment by lacasseio** [comment]
Just throwing an idea out, maybe we should handle dynamic library loading by hand so we can fallback when one doesn't work. It's a good idea to avoid creating a binary variant for those kinds of scenario as it quickly becomes out of control.

**Comment by joekiller** [comment]
Isn't the problem using termcap versus terminfo? Seems like termcap is deprecated.

**Comment by adammurdoch** [comment]
Should be fixed now.
