### ISSUE TITLE
Terminal detection failing

### ISSUE THREAD

**Issue by Vampire** [adammurdoch/native-platform#26]
When executing Gradle on Git Bash from Git for Windows, or from ConEmus conemu-cyg-32.exe (which then starts the Cygwin Bash), no progress and colors are shown, because https://github.com/adammurdoch/native-platform/blob/master/src/main/cpp/win.cpp#L404-L419 returns `false`. With plain Cygwin Bash it works fine though.

**Comment by Vampire** [comment]
At least for the ConEmu Cygwin connector it seems that the detection mechanism used here is wrong, as the handles are not WinAPI capable, but "true" posic tty handles. So I guess the detection has to be changed to handle this properly.

**Comment by adammurdoch** [comment]
The terminal handling can now detect Mintty for Cygwin and msys. Seems to be working fine with Git Bash from Git for Windows now. The fix will make its way into a Gradle release soon.

**Comment by sschuberth** [comment]
However, terminal with detection does not seem to be properly working with MinTTY / Bash from Git for Windows. If I resize the window to > 80 columns, Gradle's output is still cropped to 80 chars per line.

**Comment by adammurdoch** [comment]
Yes, it currently only detects whether the terminal is there. It does not yet know how to determine the terminal size.

**Comment by adammurdoch** [comment]
I've added #33 for the terminal size issue. I'm going to close this issue, as the changes to detect the terminal are now in Gradle (as of Gradle 5.2).
