### ISSUE TITLE
Expose a way to indicate if standard input is attached to console

### ISSUE THREAD

**Issue by bmuschko** [adammurdoch/native-platform#27]
The class `Terminals` can already detect if standard output and error is attached to console with the help of the method `isTerminal(Output)`. Additionally, a method should be available to indicate if standard input can be used from the console with the goal to know if the console is interactive or non-interactive.

**Comment by adammurdoch** [comment]
This was added in 0.15. There is now a `Terminals.isTerminalInput()` method.
